controller_manager:
  ros__parameters:
    update_rate: 10


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController


effort_controller:
  ros__parameters:
    joints:
      - Joint_1
      - Joint_2
