controller_manager:
  ros__parameters:
    update_rate: 10


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController

    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

effort_controller:
  ros__parameters:
    joints:
      - first_joint


imu_broadcaster:
  ros__parameters:

    sensor_name: link2_imu
    frame_id: imu_link